### PR TITLE
show which Volume disconnected

### LINKED ISSUE #63: When volume server is broken, master should indicate which volume is disconnected

### PR DESCRIPTION
**Pull request by guojidan**
closed #63 

just `addr: SocketAddr` can't be sure which `volume server` it is, so we need save `HeartbeatRequest` to get more information
and I think we need save the latest `HeartbeatRequest` to show latest information when volume disconnected

### CODE REVIEW

**Comment by iamazy** [comment]
https://github.com/helyim/helyim/blob/8f38a53d5824a7b38eb24025610c15b49e660f80/helyim/src/directory/server.rs#L186-L228

The `addr` corresponds to the volume one-to-one, and retaining a `HeartbeatRequest` seems to be of little use.

**Comment by guojidan** [comment]
Is it allowed for a machine to deploy multiple volume services? In the production environment a machine maybe have 36+ disk, if all disk use same volume server, can achieve full performance?

**Comment by iamazy** [comment]
> Is it allowed for a machine to deploy multiple volume services?

yes

> In the production environment a machine maybe have 36+ disk, if all disk use same volume server, can achieve full performance?

This requires testing

**Comment by guojidan** [comment]
> > Is it allowed for a machine to deploy multiple volume services?
> 
> yes

if one machine have multiple volume server, How can we confirm which `volume server` it is through IP

**Comment by iamazy** [comment]
> > > Is it allowed for a machine to deploy multiple volume services?
> > 
> > 
> > yes
> 
> if one machine have multiple volume server, How can we confirm which `volume server` it is through IP

The `addr` also contains `port`

**Comment by guojidan** [comment]
but this port is randomized

**Comment by iamazy** [comment]
> but this port is randomized

hh, sorry, the port is contained in `HeartbeatRequest`

**Comment by guojidan** [comment]
> and retaining a `HeartbeatRequest` seems to be of little use.
maybe we can just save `ip:port` `public_url` once, don't save all `HeartbeatRequest`

**Comment by iamazy** [comment]
> > and retaining a `HeartbeatRequest` seems to be of little use.
> 
> maybe we can just save `ip:port` `public_url` once, don't save all `HeartbeatRequest`

You can have a try

**Pull request closed without merging**
